const config = {
  BACKEND_URI: "http://localhost:3000",
  ENCRYPTION_KEY_ITERATIONS: 10000,
  AUTH_KEY_ITERATIONS: 500000,
  REFRESH_TOKEN_INTERVAL: 10,
  TURNSTILE_SITE_KEY: "0x4AAAAAAA_DHheOFxacY_Aq",
};
export default config;
